# Courtesy of https://github.com/crudjs/rest-nestjs-postgres/

version: '3'

services:

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:alpine
    container_name: local_db
    restart: always
    environment:
      - DB_USER=local_dev
      - DB_PASS=local_dev
    ports: 
      - 54320:5432
    volumes:
      - local_db_data:/var/lib/postgresql/data      

volumes:
  local_db_data: